#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#!/usr/bin/zsh
if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  # exec startx
  # Could use xinit instead of startx
  exec xinit -- /usr/bin/X -nolisten tcp vt7
fi
